# Generated by Django 3.2.24 on 2024-02-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusStation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='stations',
            field=models.ManyToManyField(to='BusStation.Station'),
        ),
    ]
