# Generated by Django 3.2.24 on 2024-02-13 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusStation', '0002_busroute_stations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=11, verbose_name='Данные паспорта')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='StationOfArrived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Станции прибытия маршрута',
            },
        ),
        migrations.CreateModel(
            name='StationOfDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Станции отправления маршрута',
            },
        ),
        migrations.AlterModelOptions(
            name='busroute',
            options={'verbose_name': 'Автобусный маршрут', 'verbose_name_plural': 'Автобусные маршруты'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Станция', 'verbose_name_plural': 'Станции'},
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название станции'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_departure', models.DateTimeField(verbose_name='Дата отправления')),
                ('date_of_sell', models.DateTimeField(verbose_name='Дата покупки')),
                ('seat', models.IntegerField(verbose_name='Посадочное место')),
                ('passenger', models.ManyToManyField(to='BusStation.Passenger')),
                ('station_of_arrived', models.ManyToManyField(to='BusStation.StationOfArrived')),
                ('station_of_departure', models.ManyToManyField(to='BusStation.StationOfDeparture')),
            ],
            options={
                'verbose_name': 'Станции прибытия маршрута',
            },
        ),
        migrations.AddField(
            model_name='stationofdeparture',
            name='bus_rout',
            field=models.ManyToManyField(to='BusStation.BusRoute'),
        ),
        migrations.AddField(
            model_name='stationofdeparture',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusStation.station'),
        ),
        migrations.AddField(
            model_name='stationofarrived',
            name='bus_rout',
            field=models.ManyToManyField(to='BusStation.BusRoute'),
        ),
        migrations.AddField(
            model_name='stationofarrived',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusStation.station'),
        ),
        migrations.CreateModel(
            name='RoutStations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_rout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BusStation.busroute')),
                ('stations', models.ManyToManyField(to='BusStation.Station')),
            ],
            options={
                'verbose_name': 'Промежуточные станции маршрута',
            },
        ),
    ]
