# Generated by Django 3.2.24 on 2024-03-24 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusStation', '0003_auto_20240213_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routstations',
            options={'verbose_name': 'Промежуточные станции маршрута', 'verbose_name_plural': 'Промежуточные станции маршрутов'},
        ),
        migrations.AlterModelOptions(
            name='stationofarrived',
            options={'verbose_name': 'Станции прибытия маршрута', 'verbose_name_plural': 'Станции прибытия маршрутов'},
        ),
        migrations.AlterModelOptions(
            name='stationofdeparture',
            options={'verbose_name': 'Станции отправления маршрута', 'verbose_name_plural': 'Станции отправления маршрутов'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BusStation.passenger'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='station_of_arrived',
        ),
        migrations.AddField(
            model_name='ticket',
            name='station_of_arrived',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BusStation.stationofarrived'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='station_of_departure',
        ),
        migrations.AddField(
            model_name='ticket',
            name='station_of_departure',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BusStation.stationofdeparture'),
        ),
    ]
