# Generated by Django 3.2.24 on 2024-03-26 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusStation', '0005_auto_20240326_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passengerFIO',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passengerFIO_passport',
        ),
        migrations.CreateModel(
            name='TicketNoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerFIO', models.CharField(blank=True, max_length=100, null=True)),
                ('passengerFIO_passport', models.CharField(blank=True, max_length=11, null=True)),
                ('date_of_departure', models.DateTimeField(verbose_name='Дата отправления')),
                ('date_of_sell', models.DateTimeField(verbose_name='Дата покупки')),
                ('seat', models.IntegerField(verbose_name='Посадочное место')),
                ('station_of_arrived', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BusStation.stationofarrived')),
                ('station_of_departure', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BusStation.stationofdeparture')),
            ],
        ),
    ]
