# Generated by Django 3.2.24 on 2024-03-27 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusStation', '0006_auto_20240326_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaspisanieReisov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время отправления рейса')),
                ('bus_route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='BusStation.busroute')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание рейсов',
            },
        ),
    ]
