# Generated by Django 3.2.24 on 2024-03-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusStation', '0009_auto_20240328_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='passengerFIO_passport',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passengerFIO',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО'),
        ),
    ]
