# Generated by Django 3.2.24 on 2024-03-30 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BusStation', '0010_auto_20240328_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketnologin',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
