# Generated by Django 3.2.24 on 2024-04-15 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BusStation', '0011_ticketnologin_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='aircool',
            field=models.BooleanField(default=True, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='arr_station',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrived_station2station', to='BusStation.station', verbose_name='Станция прибытия'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='depart_station',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depart_station2station', to='BusStation.station', verbose_name='Станция отправления'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание маршрута'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='size_place',
            field=models.CharField(default='стандартно', max_length=100, verbose_name='Размер пространства для ног'),
        ),
        migrations.AddField(
            model_name='busroute',
            name='toilet',
            field=models.BooleanField(default=False, verbose_name='Наличие туалета'),
        ),
        migrations.AlterField(
            model_name='busroute',
            name='stations',
            field=models.ManyToManyField(to='BusStation.Station', verbose_name='Промежуточные станции'),
        ),
    ]
